apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-iv1t
  namespace: bdettelb-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:4ddcbfc0a0844795b0a46d51087a47866e4c535b999485864a17c254fc5a843c
        name: my-python
        resources: {}
status: {}
