apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-4lzt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-4lzt
    app.kubernetes.io/part-of: my-python-app
  name: devfile-sample-python-basic-4lzt
  namespace: bdettelb-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: devfile-sample-python-basic-4lzt
    weight: null
status: {}
