apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-4lzt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-4lzt
    app.kubernetes.io/part-of: my-python-app
  name: devfile-sample-python-basic-4lzt
  namespace: bdettelb-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-sample-python-basic-4lzt
status:
  loadBalancer: {}
